### PR TITLE
[testing_master_previous] Nightly PR

### PR DESCRIPTION
**Pull request by freeipa-pr-ci2**

### CODE REVIEW

**Comment by flo-renaud** [comment]
- `test_backup_and_restore_TestBackupAndRestoreTrust`, `test_backup_and_restore_TestBackupAndRestoreWithDNS` and `test_backup_and_restore_TestBackupReinstallRestoreWithDNS` failed in `dnf install`, already reported in freeipa-pr-ci [363](https://github.com/freeipa/freeipa-pr-ci/issues/363)
- `test_idviews` failed in `ipa trust-add` with `CIFS server communication error: code "3221225506", message "{Access Denied} A process has requested access to an object but has not been granted those access rights." (both may be "None")`. @f-trivino could you check if there are CI infra issues?

**Comment by f-trivino** [comment]
>     * `test_backup_and_restore_TestBackupAndRestoreTrust`, `test_backup_and_restore_TestBackupAndRestoreWithDNS` and `test_backup_and_restore_TestBackupReinstallRestoreWithDNS` failed in `dnf install`, already reported in freeipa-pr-ci [363](https://github.com/freeipa/freeipa-pr-ci/issues/363)
> 
>     * `test_idviews` failed in `ipa trust-add` with `CIFS server communication error: code "3221225506", message "{Access Denied} A process has requested access to an object but has not been granted those access rights." (both may be "None")`. @f-trivino could you check if there are CI infra issues?

yes, willdo and update this ticket

**Comment by flo-renaud** [comment]
- `test_ipahealthcheck` also failed in `dnf install`, already reported
- 2 tests are still pending (`test_caless_TestReplicaInstall` and `test_ntp_options`)

**Comment by flo-renaud** [comment]
- `test_caless_TestReplicaInstall` and `test_ntp_options` failed on timeout

**Pull request closed without merging**
