### PR TITLE
[testing_master_previous] Nightly PR

### PR DESCRIPTION
**Pull request by freeipa-pr-ci2**

### CODE REVIEW

**Comment by miskopo** [comment]
Failure of `ipatests.test_integration.test_replica_promotion.TestUnprivilegedUserPermissions::test_client_enrollment_by_unprivileged_user` has been fixed. See https://pagure.io/freeipa/issue/8408 for detals.

**Comment by miskopo** [comment]
Test `test_integration/test_replica_promotion.py::TestUnprivilegedUserPermissions::test_sssd_config_allows_ipaapi_access_to_ifp` failed. Relevant PR #4914.
@jsf9k, could you please have a look? 
Pagure ticket: https://pagure.io/freeipa/issue/8413

**Comment by miskopo** [comment]
Test `test_integration/test_replica_promotion.py::TestReplicaPromotionLevel1::test_sssd_config_allows_ipaapi_access_to_ifp` failed. Relevant PR #4914.
@jsf9k, could you please have a look?
Pagure ticket: https://pagure.io/freeipa/issue/8414

**Comment by jsf9k** [comment]
Sorry for being late to the game here @miskopo.  This was my first PR to this project, and I'm sorry that I goofed up the tests.  Am I correct in thinking that @flo-renaud has fixed the testing issues from my PR?

**Comment by miskopo** [comment]
@jsf9k don't worry about thing, it happens to all of us :) Currently, the Pagure issue is assigned to Flo, but I am not sure about current progress there.

**Pull request closed without merging**
