### PR TITLE
[testing_ipa-4.8_latest] Nightly PR

### PR DESCRIPTION
**Pull request by freeipa-pr-ci2**

### CODE REVIEW

**Comment by fcami** [comment]
106 pending and 19 successful checks - will revisit later.

**Comment by abbra** [comment]
65 successful, 60 pending, 1 testsuite failing.

`test_integration/test_smb.py::TestSMB::test_smb_service_s4u2self` failed due to DNS resolution issues towards AD.TEST. Not sure what happens there, looks like an infrastructure issue.

There are four other failed tests in `test_smb` which we know are failing due to issues outside FreeIPA, most likely an issue with `cifs.ko`.

**Comment by abbra** [comment]
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/9474db6e-a967-11ea-a108-fa163e00cdbb/report.html also has failures which are suspiciously like infrastructure issues.

**Comment by abbra** [comment]
108 successful, 15 pending, no new failures.

**Comment by abbra** [comment]
`nfs_nsswitch_restore` is failing for at least a month.

**Comment by abbra** [comment]
Same with `test_otp`

**Comment by fcami** [comment]
- nfs_nsswitch_restore issue already reported: https://pagure.io/freeipa/issue/8189
-

**Comment by flo-renaud** [comment]
- `test_otp` failure already reported in [8304](https://pagure.io/freeipa/issue/8304)
- `test_smb` failure already reported in [8184](https://pagure.io/freeipa/issue/8184)
- `test_sssd` failure already reported in [8294](https://pagure.io/freeipa/issue/82940
- `test_trust`: 1 failure already reported in [8354](https://pagure.io/freeipa/issue/8354), but there are also additional failures with sudomain or treedomain trusts, reported in [8365](https://pagure.io/freeipa/issue/8365)

**Comment by flo-renaud** [comment]
All the test failures have been reported.

**Pull request closed without merging**
