### PR TITLE
Troubleshoot Selenium error

### PR DESCRIPTION
**Pull request by netoarmando**
Issue: https://pagure.io/freeipa/issue/8473

Signed-off-by: Armando Neto <abiagion@redhat.com>

### CODE REVIEW

**Comment by netoarmando** [comment]
@flo-renaud the latest runs are already using the new templates, but apparently I'm hitting a regression during installation because of `pki-server acme-deploy`. Do you think it's okay to proceed?

If so, I will open the following PRs:
https://github.com/freeipa/freeipa/compare/ipa-4-8...netoarmando:2020-08-27-bump-ipa-4-8-template-version?expand=1
https://github.com/freeipa/freeipa/compare/master...netoarmando:2020-08-27-bump-master-template-version?expand=1

**Comment by flo-renaud** [comment]
> I'm hitting a regression during installation because of pki-server acme-deploy. Do you think it's okay to proceed?

The regression happens because pki 10.10 is installed in the vagrant image but we are missing a dependency on pki-acme (please see https://github.com/freeipa/freeipa/pull/5039).
Is the template enabling @freeipa/freeipa-master copr repo? If that's the case, then it is also pulling pki 10.10 from @pki/master and the spec file needs to add the dependency on pki-acme.

**Comment by netoarmando** [comment]
> Is the template enabling @freeipa/freeipa-master copr repo? If that's the case, then it is also pulling pki 10.10 from @pki/master and the spec file needs to add the dependency on pki-acme.

Yes, `@freeipa/freeipa-master` is enabled as expected. I added a comment to the PR you mentioned. Thanks.

**Comment by netoarmando** [comment]
Final PRs to update freeipa:
- `master`: https://github.com/freeipa/freeipa/pull/5072
- `ipa-4-8`: https://github.com/freeipa/freeipa/pull/5073

**Pull request closed without merging**
