### PR TITLE
Test Rawhide nightly jobs

### PR DESCRIPTION
**Pull request by netoarmando**
Test latest template for Fedora Rawhide nightly compose

Signed-off-by: Armando Neto <abiagion@redhat.com>

### CODE REVIEW

**Comment by flo-renaud** [comment]
Adding rerun since the build timed out

**Comment by netoarmando** [comment]
@flo-renaud Rawhide template is now working again (after https://github.com/freeipa/freeipa/pull/5270).

**Comment by flo-renaud** [comment]
@netoarmando thanks for the update. Many test failures are known issues that shouldn't prevent us from updating the template in ipatests/prci_definitions/nightly_rawhide.yaml in freeipa's repo. You can go ahead and create a PR in order to use the new template.

**Comment by netoarmando** [comment]
> @netoarmando thanks for the update. Many test failures are known issues that shouldn't prevent us from updating the template in ipatests/prci_definitions/nightly_rawhide.yaml in freeipa's repo. You can go ahead and create a PR in order to use the new template.

Already included in https://github.com/freeipa/freeipa/pull/5187. Closing this.

**Pull request closed without merging**
