### PR TITLE
Test DS builds 2097561

### PR DESCRIPTION
**Pull request by flo-renaud**
Tentative fix for https://github.com/389ds/389-ds-base/issues/4680
389ds coredump (@389ds/389-ds-base-nightly) in replica install with CA

### CODE REVIEW

**Comment by flo-renaud** [comment]
@progier389
The test build does not fix the issue, we still have a coredump on the replica during the installation. See for instance the test [simple_replication](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/2821235a-8d87-11eb-a19e-fa163e057486/test_integration-test_simple_replication.py-TestSimpleReplication-install/replica0.ipa.test/journal.gz)

**Comment by progier389** [comment]
Thank you Florence, the crash was expected as I only added some traces but
  the weird thing is that I did not see any of them in the log while the core stack says that we are inside the function ( within bdb_public_cursor_bulkop only bdb_dbt2dbival calls dblayer_value_set_buffer in which the crash occurs ... ) 
 And I just double checked: 
    the diff is within the code that I built and the copr number is OK ...
  So either the log at ERR level are not logged for some reason or there is something behind the scene and we are not running the binaries that we expect ... 
  
  I will check on my side to see if the logs are logged with my packages ...
  

```
diff --git a/ldap/servers/slapd/back-ldbm/db-bdb/bdb_layer.c b/ldap/servers/slapd/back-ldbm/db-bdb/bdb_layer.c
index f2a62ac24..ce0ad0570 100644
--- a/ldap/servers/slapd/back-ldbm/db-bdb/bdb_layer.c
+++ b/ldap/servers/slapd/back-ldbm/db-bdb/bdb_layer.c
@@ -6432,8 +6432,21 @@ int bdb_public_cursor_bulkop(dbi_cursor_t *cursor,  dbi_op_t op, dbi_val_t *key,
     if (bdb_cur == NULL)
         return DBI_RC_INVALID;
 
+#define A(a)   ((uint64_t)(a))
+
+    slapi_log_err(SLAPI_LOG_ERR, "bdb_public_cursor_bulkop", "[%d] dbi key = 0x%lX flags = 0x%x data = 0X%lx size = %ld ulen = %ld\n",
+        __LINE__, A(key), key->flags, A(key->data), key->size, key->ulen);
+    slapi_log_err(SLAPI_LOG_ERR, "bdb_public_cursor_bulkop", "[%d] dbi bulkdata = 0x%lX flags = 0x%x data = 0X%lx size = %ld ulen = %ld\n",
+        __LINE__, A(&bulkdata->v), bulkdata->v.flags, A(bulkdata->v.data), bulkdata->v.size, bulkdata->v.ulen);
+
     bdb_dbival2dbt(key, &bdb_key, PR_FALSE);
     bdb_dbival2dbt(&bulkdata->v, &bdb_data, PR_FALSE);
+
+    slapi_log_err(SLAPI_LOG_ERR, "bdb_public_cursor_bulkop", "[%d] dbt bdb_key = 0x%lX flags = 0x%x data = 0X%lx size = %d ulen = %d\n",
+        __LINE__, A(&bdb_key), bdb_key.flags, A(bdb_key.data), bdb_key.size, bdb_key.ulen);
+    slapi_log_err(SLAPI_LOG_ERR, "bdb_public_cursor_bulkop", "[%d] dbt bulkdata = 0x%lX flags = 0x%x data = 0X%lx size = %d ulen = %d\n",
+        __LINE__, A(&bdb_data), bdb_data.flags, A(bdb_data.data), bdb_data.size, bdb_data.ulen);
+
     switch (op)
     {
         case DBI_OP_MOVE_TO_KEY:
@@ -6455,8 +6468,24 @@ int bdb_public_cursor_bulkop(dbi_cursor_t *cursor,  dbi_op_t op, dbi_val_t *key,
             rc = DBI_RC_UNSUPPORTED;
             break;
     }
+
+    slapi_log_err(SLAPI_LOG_ERR, "bdb_public_cursor_bulkop", "[%d] dbt bdb_key = 0x%lX flags = 0x%x data = 0X%lx size = %d ulen = %d\n",
+        __LINE__, A(&bdb_key), bdb_key.flags, A(bdb_key.data), bdb_key.size, bdb_key.ulen);
+    slapi_log_err(SLAPI_LOG_ERR, "bdb_public_cursor_bulkop", "[%d] dbt bulkdata = 0x%lX flags = 0x%x data = 0X%lx size = %d ulen = %d\n",
+        __LINE__, A(&bdb_data), bdb_data.flags, A(bdb_data.data), bdb_data.size, bdb_data.ulen);
+    slapi_log_err(SLAPI_LOG_ERR, "bdb_public_cursor_bulkop", "[%d] dbi key = 0x%lX flags = 0x%x data = 0X%lx size = %ld ulen = %ld\n",
+        __LINE__, A(key), key->flags, A(key->data), key->size, key->ulen);
+    slapi_log_err(SLAPI_LOG_ERR, "bdb_public_cursor_bulkop", "[%d] dbi bulkdata = 0x%lX flags = 0x%x data = 0X%lx size = %ld ulen = %ld\n",
+        __LINE__, A(&bulkdata->v), bulkdata->v.flags, A(bulkdata->v.data), bulkdata->v.size, bulkdata->v.ulen);
+
     bdb_dbt2dbival(&bdb_key, key, PR_TRUE);
     bdb_dbt2dbival(&bdb_data, &bulkdata->v, PR_TRUE);
+
+    slapi_log_err(SLAPI_LOG_ERR, "bdb_public_cursor_bulkop", "[%d] dbi key = 0x%lX flags = 0x%x data = 0X%lx size = %ld ulen = %ld\n",
+        __LINE__, A(key), key->flags, A(key->data), key->size, key->ulen);
+    slapi_log_err(SLAPI_LOG_ERR, "bdb_public_cursor_bulkop", "[%d] dbi bulkdata = 0x%lX flags = 0x%x data = 0X%lx size = %ld ulen = %ld\n",
+        __LINE__, A(&bulkdata->v), bulkdata->v.flags, A(bulkdata->v.data), bulkdata->v.size, bulkdata->v.ulen);
+
     return bdb_map_error(__FUNCTION__, rc);
 }

```

**Comment by progier389** [comment]
When building then installing a 2 suppliers topology (usign dscreate+dsconf) on my local I see the added logs (on both suppliers) 
grep bdb_public_cursor_bulkop sl*/errors
slapd-master1/errors:[26/Mar/2021:17:34:41.815098094 +0100] - ERR - bdb_public_cursor_bulkop - [6438] dbi key = 0x7F8E01E28BA0 flags = 0x3 data = 0X7f8e01e2b1a0 size = 37 ulen = 37
...
slapd-master2/errors:[26/Mar/2021:17:35:45.652960664 +0100] - ERR - bdb_public_cursor_bulkop - [6487] dbi bulkdata = 0x7FE1D77B60C8 flags = 0xb data = 0X7fe1d77b6110 size = 8192 ulen = 8192
But I do not find them in that test .

And I also extracted the rpm with rpm2cpio and saw that the source also contains the added logs

So at this point I suspect that there is something wrong with the way we do the test.
It looks as if some old version get used instead of the copr build (unless copr built wrong version rather than using the rpm ?)

**Comment by flo-renaud** [comment]
Hi @progier389 
I tested manually with the build from the copr repo, same issue and no additional logs in /var/log/dirsrv/slapd*/errors. If you need help I can show you how to install ipa server + replica on lab machines where you will be able to use gdb.
Note that the issue happens when the replica also has a CA role, meaning that there are 2 backends on each 389-ds server: one for the normal suffix and one for o=ipaca.

**Pull request closed without merging**
