### PR TITLE
Test DS builds 2112236 

### PR DESCRIPTION
**Pull request by flo-renaud**
Debug #4700 Regression in winsync replication agreement

### CODE REVIEW

**Comment by flo-renaud** [comment]
Results with build 2108292 are available [here](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/d06a2968-9150-11eb-bf8e-fa163e5185d3)

**Comment by flo-renaud** [comment]
@tbordaz
Results with build 2109983 (389-ds-base-1.4.4.11_up_to_14f67ebeb-20210331git3965cb73a.fc33.x86_64) are green: [Details](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/d6f33818-92b5-11eb-b080-fa163e35ece8)

**Comment by flo-renaud** [comment]
@tbordaz Results with build [2112236](https://copr.fedorainfracloud.org/coprs/g/389ds/389-ds-base-nightly/build/2112236/) are also green: [Details](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/a6de5c8c-92f8-11eb-9713-fa163e0320b2). This one seems a good candidate :partying_face:

**Comment by tbordaz** [comment]
@flo-renaud yes indeed. Thanks for all the 5 or 6 copr builds run !!!
Huge efffort.
I am preparing a PR to revert breaking portion of that fix. Surprisingly this fix is quite old and it looks that only sidgen reveal that error. I was not able to reproduce it myself.

**Pull request closed without merging**
