### PR TITLE
[testing_master_testing_selinux] Nightly PR

### PR DESCRIPTION
**Pull request by freeipa-pr-ci2**

### CODE REVIEW

**Comment by pvoborni** [comment]
Was looking at the "testing-fedora/test_ipahealthcheck — RunPytest timed out after 5400s " and I think the job needs slight higher timeout, e.g. by 20 mins. The actual test finished well - in the time but it was killed by the timeout when uploading artifacts.

**Comment by amore17** [comment]
> Was looking at the "testing-fedora/test_ipahealthcheck — RunPytest timed out after 5400s " and I think the job needs slight higher timeout, e.g. by 20 mins. The actual test finished well - in the time but it was killed by the timeout when uploading artifacts.
Yes already reported new issue https://pagure.io/freeipa/issue/9362 to fix timeout

**Comment by amore17** [comment]
> I'm investigating the "vagrant up --no-provision --parallel" exited with error code 1" it looks as something runner specific.

Should i rerun this job ?
you can use [logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/9ccd946a-e477-11ed-a16c-fa163edbd2c4) for debugging

**Comment by pvoborni** [comment]
You can re-run.

**Pull request closed without merging**
