### PR TITLE
[testing_master_testing] Nightly PR

### PR DESCRIPTION
**Pull request by freeipa-pr-ci2**

### CODE REVIEW

**Comment by flo-renaud** [comment]
- 4 tests failed on infra issues (failed to publish artifacts, timeout or in `vagrant provision`): `test_http_kdc_proxy`, `test_installation_TestInstallWithCA_KRA2`, `test_sssd` and `test_trust`
- `nfs_nsswitch_restore` failure already reported in [8189](https://pagure.io/freeipa/issue/8189)
- `test_crlgen_manage` is a new failure, reported in dogtagpki [3182](https://pagure.io/dogtagpki/issue/3182)
- `test_fips` failure already reported in [8387](https://pagure.io/freeipa/issue/8387)
- `test_idviews` failed in ipa-server-install with a timeout getting RA cert, already reported in [8096](https://pagure.io/freeipa/issue/8096)
- `test_ipahealthcheck` failure already reported in [8386](https://pagure.io/freeipa/issue/8386)
- `test_smb` failures already reported in [8344](https://pagure.io/freeipa/issue/8344) and [8184](https://pagure.io/freeipa/issue/8184)
- `test_webui_general` failed in the setup, with a TimeoutException in  selenium driver. @serg-cymbaluk could you have a look?

**Comment by serg-cymbaluk** [comment]
> test_webui_general failed in the setup, with a TimeoutException in selenium driver

The issue can happen from time to time when the VM instance has some lags.

Changing internal timeouts or adding some retries would not be effective in the case, because these values are unpredictable there.

**Comment by flo-renaud** [comment]
@netoarmando @f-trivino 
A few tests are blocked in pending state, and it looks like build has been re-triggered. Could you check what went wrong?

**Comment by netoarmando** [comment]
> @netoarmando @f-trivino
> A few tests are blocked in pending state, and it looks like build has been re-triggered. Could you check what went wrong?

Pending jobs have the prefix `fedora-latest/`, some instance of PR-CI couldn't fetch the definitions from this commit and the fallback is to fetch from base branch, which is `master`. So, those jobs were added to this PR, it's ugly but safe to ignore them.

Provision errors on topologies requiring AD happened due to a problem downloading cygwin, I'll need to investigate it: https://github.com/freeipa/freeipa-pr-ci/issues/382

**Pull request closed without merging**
