### PR TITLE
Testing spichugi/pyasn1-0.5.1-rc1-test

### PR DESCRIPTION
**Pull request by droideck**

### CODE REVIEW

**Comment by droideck** [comment]
@flo-renaud hi! When you have time, could you please check the failures?
I think they are no related to `pyasn1`... There are some examples:

```
ipa: ERROR: stderr: Checking DNS domain ipa.test., please wait ...
DNS server 192.168.122.1: query '. SOA': The resolution lifetime expired after 10.111 seconds: Server 192.168.122.1 UDP port 53 answered The DNS operation timed out.
DNS server 192.168.122.1: query '. SOA': The resolution lifetime expired after 10.111 seconds: Server 192.168.122.1 UDP port 53 answered The DNS operation timed out.
---
CRITICAL: ipahealthcheck.ipa.certs.IPACertfileExpirationCheck: can't compare offset-naive and offset-aware datetimes - Known bug?..
---
[ipa: WARNING: ipa: ERROR: DNS zone with name "122.168.192.in-addr.arpa." already exists
ipa: ERROR: stderr: Lookup failed: Preferred host replica2.ipa.test does not provide DNS.](host.py:201 stderr: Invalid IP address fe80::8d68:f99f:dc28:a917 for master.ipa.test.: cannot use link-local IP address fe80::8d68:f99f:dc28:a917)
---
[E           AssertionError: Record does not exist: host-b1578401.ipa.test
](ipa: ERROR: stderr: Invalid IP address fe80::5702:4aab:97e1:27a4 for master.ipa.test.: cannot use link-local IP address fe80::5702:4aab:97e1:27a4)
---
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.StaleElementReferenceException: Message: The element with the reference d02dfc9f-785b-4388-b480-d80124d9dfe2 is stale; either its node document is not the active document, or it is no longer connected to the DOM
E       Stacktrace:
E       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
E       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:188:5
E       StaleElementReferenceError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:660:5
E       getKnownElement@chrome://remote/content/marionette/json.sys.mjs:286:11
E       deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:233:20
E       cloneObject@chrome://remote/content/marionette/json.sys.mjs:54:24
E       deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:240:16
E       cloneObject@chrome://remote/content/marionette/json.sys.mjs:54:24
E       deserializeJSON@chrome://remote/content/marionette/json.sys.mjs:240:16
E       json.deserialize@chrome://remote/content/marionette/json.sys.mjs:244:10
E       receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:72:30
---
Some strange RUV and assert exceptions... 
---
self = <ipatests.test_webui.test_selfservice.test_selfservice object at 0x7fce1b72fd90>

    @screenshot
    def test_permission_using_enter_key(self):
        """
        Try to add/delete persmission using enter key
        """
        # try to add using enter key
        self.init_app()
        self.add_record(data_selfservice.ENTITY,
                        data_selfservice.DATA1,
                        dialog_btn=None)
        actions = ActionChains(self.driver)
        actions.send_keys(Keys.ENTER).perform()
        self.wait()
        self.assert_notification(assert_text=SERVICE_ADDED)
>       self.assert_record(data_selfservice.DATA1['pkey'])

test_webui/test_selfservice.py:244: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ipatests.test_webui.test_selfservice.test_selfservice object at 0x7fce1b72fd90>
pkey = 'itest-selfservice-rule1', parent = None, table_name = None
negative = False

    def assert_record(self, pkey, parent=None, table_name=None, negative=False):
        """
        Assert that record is in current search table
        """
        has = self.has_record(pkey, parent, table_name)
        has |= self.has_record(pkey.lower(), parent, table_name)
        if negative:
            assert not has, "Record exists when it shouldn't: %s" % pkey
        else:
>           assert has, 'Record does not exist: %s' % pkey
E           AssertionError: Record does not exist: itest-selfservice-rule1

test_webui/ui_driver.py:2204: AssertionError
```

So unless I miss something, the tested pyasn1 version that I prepare for a release looks good IPA-wise, does it?

**Comment by flo-renaud** [comment]
Hi @droideck 
- the errors for `test_ipahealthcheck`, `test_ipahealthcheck_cli_fsspace` and `test_replica_promotion_TestHiddenReplicaPromotion` are known issues, unrelated to your changes ([9400](https://pagure.io/freeipa/issue/9400) and [298](https://github.com/freeipa/freeipa-healthcheck/issues/298)).
- `test_nfs` should be commented out in your patch. In this run it conflicts with the previous test definition and makes `test_pki_config_override` fail
- `test_topology_TestCASpecificRUVs` is a known issue ([8023](https://pagure.io/freeipa/issue/8023))
- I relaunched the other tests, the failures may be transient issues

**Comment by droideck** [comment]
> * `test_nfs` should be commented out in your patch. In this run it conflicts with the previous test definition and makes `test_pki_config_override` fail

Thanks for the review!
I commented out the test and it made it rerun once more.
Now, it's `1 errored, 8 failing` instead of `6 failing`. But as I haven't changed anything in the builds, I think we are good FreeIPA-wise, aren't we?

**Comment by flo-renaud** [comment]
@droideck 
I reran some of the (unexpectedly) failing tests and the CI has now reached a good state where the only failures are known test issues. The new version of pyasn1-0.5.0-rc051 doesn't introduce any regression. You can go ahead and submit the update.

**Pull request closed without merging**
