### PR TITLE
Test 389-ds copr build

### PR DESCRIPTION
**Pull request by flo-renaud**
https://copr.fedorainfracloud.org/coprs/g/389ds/389-ds-base-nightly/build/3196603/

### CODE REVIEW

**Comment by flo-renaud** [comment]
For future ref, the copr build was used to test a fix for https://bugzilla.redhat.com/show_bug.cgi?id=2027730 (SELinux is preventing ns-slapd access to /dev/shm/slapd-IPA-TEST/DBVERSION). The bug impacts ipa-restore in selinux enforcing mode.

**Comment by rcritten** [comment]
I manually tested on F35 with a new build and the restore was successful. 

This build worked for me: 389-ds-base-2.1.0-202201201917gitad63d7a10

**Comment by flo-renaud** [comment]
Re-launching the tests with the newer build [3209460](https://copr.fedorainfracloud.org/coprs/g/389ds/389-ds-base-nightly/build/3209460/) with contains `389-ds-base-2.1.0-202201201917gitad63d7a10`.

**Comment by flo-renaud** [comment]
@rcritten @mreynolds389 the tests look way better with the latest test build.
`test_replica_promotion_TestHiddenReplicaPromotion` error has already be seen using 389ds copr repo (in [this](https://github.com/freeipa-pr-ci2/freeipa/pull/1444) nightly test and can be ignored, completely unrelated to the code changes.
Right now there are still 6 pending tests, I'll continue monitoring them and will keep you posted.

**Comment by flo-renaud** [comment]
The other tests completed successfully, only `test_replica_promotion_TestHiddenReplicaPromotion` failed with a known issue

**Pull request closed without merging**
